twitter:
  consumer_key: "YOUR_TWITTER_API_KEY"
  consumer_secret: "YOUR_TWITTER_API_SECRET"
  access_token: "YOUR_ACCESS_TOKEN"
  access_token_secret: "YOUR_ACCESS_TOKEN_SECRET"

vk:
  access_token: "YOUR_VK_SERVICE_TOKEN"
  api_version: "5.131"

settings:
  max_users: 500
  edge_threshold: 3